-- drizzle-kit's autogenerated INSERT ... SELECT for both table recreates
-- below originally selected `"academic_year"` (and, for buckets,
-- `"include_specialisation_members"`) straight from the pre-migration
-- table — but those are the columns this migration is adding, so the old
-- table doesn't have them yet and the generated SQL fails at migrate time
-- with "no such column". Hand-fixed to select the literal default (2026 /
-- false) instead. Harmless either way: `buckets` and `bucket_members` are
-- reference data, wholesale replaced by `seedReferenceData()` immediately
-- after migration on every boot, so nothing depends on these particular
-- copied values surviving.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_bucket_members` (
	`bucket_key` text NOT NULL,
	`academic_year` integer DEFAULT 2026 NOT NULL,
	`course_code` text NOT NULL,
	PRIMARY KEY(`bucket_key`, `academic_year`, `course_code`)
);
--> statement-breakpoint
INSERT INTO `__new_bucket_members`("bucket_key", "academic_year", "course_code") SELECT "bucket_key", 2026, "course_code" FROM `bucket_members`;--> statement-breakpoint
DROP TABLE `bucket_members`;--> statement-breakpoint
ALTER TABLE `__new_bucket_members` RENAME TO `bucket_members`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE TABLE `__new_buckets` (
	`key` text NOT NULL,
	`academic_year` integer DEFAULT 2026 NOT NULL,
	`program_code` text NOT NULL,
	`label` text NOT NULL,
	`min_units` integer NOT NULL,
	`cap_units` integer NOT NULL,
	`kind` text NOT NULL,
	`mode` text NOT NULL,
	`exclusive` integer DEFAULT false NOT NULL,
	`subjects` text DEFAULT '' NOT NULL,
	`min_level` integer,
	`max_level` integer,
	`include_specialisation_members` integer DEFAULT false NOT NULL,
	`sort_order` integer NOT NULL,
	PRIMARY KEY(`key`, `academic_year`)
);
--> statement-breakpoint
INSERT INTO `__new_buckets`("key", "academic_year", "program_code", "label", "min_units", "cap_units", "kind", "mode", "exclusive", "subjects", "min_level", "max_level", "include_specialisation_members", "sort_order") SELECT "key", 2026, "program_code", "label", "min_units", "cap_units", "kind", "mode", "exclusive", "subjects", "min_level", "max_level", false, "sort_order" FROM `buckets`;--> statement-breakpoint
DROP TABLE `buckets`;--> statement-breakpoint
ALTER TABLE `__new_buckets` RENAME TO `buckets`;--> statement-breakpoint
ALTER TABLE `plans` ADD `commencement_year` integer DEFAULT 2026 NOT NULL;